// spa/components/FileListItem.vue
<script setup lang="ts">
import type { DocumentFile } from '../types/files'

interface Props {
  documents: DocumentFile[]
  fileType: 'photo' | 'visa' | 'identity_document'
}

const props = defineProps<Props>()

const emit = defineEmits<{
  (e: 'deleteFile', id: number, type: Props['fileType']): void
}>()

const onDeleteClick = (id: number) => {
  emit('deleteFile', id, props.fileType)
}
</script>

<template>
  <div>
    <h3>Uploaded Files</h3>
    <div class="border mt-3 mb-2">
      <div
        v-for="item in documents"
        :key="item.id"
        class="d-flex justify-space-between align-center py-2 px-4"
        :class="{ 'border-b': documents.indexOf(item) < documents.length - 1 }"
      >
        <div class="d-flex align-center">
          <v-icon v-if="!item.url" class="mr-2" size="24" color="gray"
            >mdi-file-document-outline</v-icon
          >
          <img v-else :src="item.url" class="mr-2" width="24" height="24" />
          <span>{{ item.name }}</span>
        </div>
        <v-btn
          icon="mdi-delete-outline"
          variant="plain"
          :ripple="false"
          @click="onDeleteClick(item.id)"
        />
      </div>
    </div>
  </div>
</template>

// spa-react/app/components/FileListItem.tsx
import React, { useCallback } from "react";
import { Box, Typography, IconButton } from "@mui/material";
import InsertDriveFileOutlinedIcon from "@mui/icons-material/InsertDriveFileOutlined";
import DeleteOutlineIcon from "@mui/icons-material/DeleteOutline";
import type { DocumentFile, DocumentType } from "../../types/files";

interface FileListItemProps {
  documents: DocumentFile[];
  fileType: DocumentType;
  onDeleteFile: (id: number, type: DocumentType) => void;
}

const FileListItem: React.FC<FileListItemProps> = ({
  documents,
  fileType,
  onDeleteFile,
}) => {
  const onDeleteClick = useCallback(
    (id: number) => {
      onDeleteFile(id, fileType);
    },
    [onDeleteFile, fileType]
  );

  return (
    <Box>
      <Typography variant="h6" component="h3" mb={1}>
        Uploaded Files
      </Typography>
      <Box border={1} borderColor="grey.300" mt={1.5} mb={1}>
        {documents.map((item, index) => (
          <Box
            key={item.id}
            display="flex"
            justifyContent="space-between"
            alignItems="center"
            py={1}
            px={2}
            sx={{
              borderBottom:
                index < documents.length - 1 ? "1px solid #e0e0e0" : "none",
            }}
          >
            <Box display="flex" alignItems="center">
              {item.url ? (
                <img
                  src={item.url}
                  alt={item.name}
                  style={{ marginRight: 8, width: 24, height: 24 }}
                />
              ) : (
                <InsertDriveFileOutlinedIcon sx={{ mr: 1, fontSize: 24 }} />
              )}
              <Typography variant="body1">{`${item.name
                .substring(0, 24)
                .trim()}...`}</Typography>
            </Box>
            <IconButton size="small" onClick={() => onDeleteClick(item.id)}>
              <DeleteOutlineIcon />
            </IconButton>
          </Box>
        ))}
      </Box>
    </Box>
  );
};

export default FileListItem;
